# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
cache: true
# Site title and description
title:              JiBrok
description:        "JiBrok develops powerful Jira apps and add-ons for Atlassian Cloud and Data Center. Time tracking, custom fields, message displays, timers, and workflow automation tools for enhanced project management."
lang:               en

# Site subpath, e.g. /blog
baseurl:            ""

# Permalink URLs structure, for permalink style options see: https://jekyllrb.com/docs/permalinks/
permalink:          /:title/

# Site base hostname & protocol, e.g. http://example.com
url:                "https://jibrok.com"

# Site logo # e.g. logo.png, upload logo image file to /uploads/ folder
logo: vendor/vendor-logo-with-white-background-1000px.png

navbar:
    sticky:         true
    search:         true
  
# Default author settings
author:
    name:           JiBrok
    title:          Lead Developer  
    avatar:         vendor/jibrok-logo-with-white-background-144px.png

# Author settings, displayed on post and doc pages if front matter references author name e.g. author: peter
authors:
    jibrok:
      name:         JiBrok
      title:        Lead Developer
      avatar:       vendor/jibrok-logo-with-white-background-144px.png
#    evan:
#      name:         Evan Wells
#      title:        Support
#      avatar:       avatar-evan.png
#    sara:
#      name:         Sara Galen
#      title:        Lead Developer
#      avatar:       avatar-sara.png
#    alex:
#      name:         Alex Koch
#      title:        Design Engineer
#      avatar:       avatar-alex.png
#    daniel:
#      name:         Daniel Shultz
#      title:        Developer
#      avatar:       avatar-daniel.png
#    tom:
#      name:         Tom Farrell
#      title:        Developer
#      avatar:       avatar-tom.png

# Social icons displayed in footer
social:
    email: support@jibrok.com
    website:
  #facebook: https://www.facebook.com/ji.brok.apps
    flickr:
    dribbble:
    github: https://github.com/JiBrok
    googleplus:
    instagram:
    linkedin:
    pinterest:
#    twitter: https://twitter.com/JiBrok_apps
    vimeo:
#    youtube: https://www.youtube.com/channel/UCtqfbNU2XWiftZ9ev_AaJCg
    rss: https://jibrok.com/feed.xml
    #slack: https://join.slack.com/t/jibrok/shared_invite/zt-h94es09e-oaNGiM5ZAS~b3ieOGIgUkA

# Share button
share:
    post:           true # Display share buttons on a post page
    doc:            true # Display share buttons on a doc page
    twitter:        true # Enable by setting true 
    facebook:       true # Enable by setting true (Facebook handle not required)

# Default footer image settings
footer:
    copyright:      # Made by <a href="https://unbound.studio/">Unbound Studio</a> in Cleveland.

# Disqus comments shortname, requires Disqus account https://disqus.com/
disqus:
    shortname:      # 1234

# Google analytics code, get your code here https://www.google.com/analytics/
google_analytics:

# Number of posts displayed on blog page
paginate:           10

# Blog path
paginate_path:      "/blog/:num/"

# Path to post content assets directory i.e post images, pdfs etc
uploads:            /uploads/

# Build settings
markdown:           kramdown
highlighter:        rouge

# Kramdown settings for automatic heading anchors
kramdown:
  auto_ids: true
  header_offset: 0
  toc_levels: 1..6
  
# SEO improvements  
twitter:
  username: JiBrok_apps

# Better image handling
image_optim:
  pngout: false
  svgo: false

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-gist
  - jekyll-avatar
  - jekyll-sitemap
#  - jekyll-json-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules

sass:
  style:            compressed

collections:
  docs:
    output:         true
  faqs:
    output:         false
  changelogs:
    output:         false

# Defaults
defaults:
  # _posts
  - scope:
      path:         ""
      type:         posts
    values:
      layout:       post
  # _docs
  - scope:
      path:         ""
      type:         docs
    values:
      layout:       doc
